sudo: required
language: node_js
node_js:
  - "10"
  - "12"
matrix:
  allow_failures:
  - node_js: "10"
jdk:
  - openjdk11
before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz && tar -xvzf apache-cassandra-3.11.4-bin.tar.gz
  - sudo sh ./apache-cassandra-3.11.4/bin/cassandra -R
  - sleep 20
